name: weatherly
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  lottie: ^3.1.3
  logger: ^2.4.0
  flutter_gen: ^5.8.0
  build_runner: ^2.4.13
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations.
flutter:
  uses-material-design: true

  # Define assets to include.
  assets:
    - assets/fonts/
    - assets/lotties/

  # Add custom fonts.
  fonts:
    - family: LEDDotMatrix
      fonts:
        - asset: assets/fonts/LED Dot-Matrix 400.ttf
